web:
  container_name: errbit_web
  build: .
  links:
    - mongo
  environment:
    - VIRTUAL_HOST=errbit.test
    - SECRET_KEY_BASE=foobar
    - ERRBIT_HOST=errbit.test
    - ERRBIT_PROTOCOL=https
    - MONGO_URL=mongodb://mongo/errbit

mongo:
  container_name: errbit_mongo
  image: mongo:latest
